name: C++ and C# CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_cpp:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up C++ environment
      run: sudo apt-get update && sudo apt-get install build-essential
    - name: Build C++ project
      run: |
        g++ -o myCppApp myCppSource.cpp
        ./myCppApp

  build_csharp:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.301' # Set this to your .NET Core version
    - name: Build C# project
      run: dotnet build MyCsharpProject.sln
    - name: Run C# project
      run: dotnet run --project MyCsharpProject/MyCsharpProject.csproj
