name: Build and Run C++ and C# Projects

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_run:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    # Set up MSBuild
    - name: Set up MSBuild path
      uses: microsoft/setup-msbuild@v1.0.2

    # Build C++ project
    - name: Build C++ project
      run: msbuild TestDraco.sln -property:Configuration=Release -property:Platform="x64" -target:DracoWrapper

    - name: Create NuGet package
      run: |
        nuget pack Nuget/Draco_transcoder.nuspec -Properties Configuration=Release

    - name: Push NuGet package
      run: |
        nuget push *.nupkg -Source "github" -ApiKey ${{secrets.NUGET_TOKEN_EVERSE}}

